[build]
  command = "mkdir -p public && echo 'ok' > public/index.html"
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/comment/:splat"
  status = 200
